site_name: KwikPOS Developer Guide
theme: shadcn
plugins:
  - search
  - excalidraw
nav:
  - Developer Guide: index.md
  - Getting Started: getting-started.md
  - Prerequisites: prerequisites.md
  - Projects:
      - KwikPOS Live (Backend): projects/kwikpos-live.md
      - KwikPOS API (Kiosk Adapter): projects/kwikpos-api.md
