site_name: KwikPOS Developer Guide
site_url: https://adrnmlgrto-oct.github.io/kwikpos-development-guide/
repo_url: https://github.com/adrnmlgrto-oct/kwikpos-development-guide
theme: shadcn
plugins:
  - search
  - excalidraw
nav:
  - Developer Guide: index.md
  - Getting Started: getting-started.md
  - Prerequisites: prerequisites.md
  - Projects:
      - KwikPOS Live (Backend): projects/kwikpos-live.md
      - KwikPOS API (Kiosk Adapter): projects/kwikpos-api.md
