[project]
name = "kwikpos-development-guide"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-shadcn>=0.9.8",
    "mkdocs-video>=1.5.0",
]
